// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient(): SupabaseClient<Database> | null {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['VITE_SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['VITE_SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    // Degrade gracefully: log a warning but do NOT throw. The whole site
    // would otherwise crash on hydration whenever the build was missing
    // these env vars (e.g. a brand-new Vercel project that hasn't had its
    // environment variables configured yet).
    console.warn(
      `[Supabase] Missing env var(s): ${missing.join(', ')}. ` +
      `Sign-in / payments are disabled. Add them in Vercel → Settings → ` +
      `Environment Variables and redeploy.`,
    );
    return null;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: SupabaseClient<Database> | null | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
//
// When env vars are missing, the proxy returns a stub that throws a clear,
// non-fatal error on use. This keeps the rest of the site (home page,
// static content, navigation) rendering instead of crashing the whole app.
export const supabase = new Proxy({} as SupabaseClient<Database>, {
  get(_target, prop, receiver) {
    if (_supabase === undefined) _supabase = createSupabaseClient();
    if (_supabase === null) {
      throw new Error(
        `Supabase is not configured (cannot call "${String(prop)}"). ` +
        `Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in ` +
        `Vercel → Settings → Environment Variables.`,
      );
    }
    return Reflect.get(_supabase, prop, receiver);
  },
});

